version: '3.8'

networks:
  app_net:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3


  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    restart: always
    depends_on:
      - auth-service
    environment:
      GRPC_SERVER_ADDRESS: "auth-service:57442"
      HTTP_PORT: "8080"
    ports:
      - "8080:8080"


  authdb:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  auth-service:
    build:
      context: .
      dockerfile: ./authService/Dockerfile
    restart: always
    depends_on:
      - authdb
      - redis
    environment:
      ENV: ${ENV}
      GRPC_PORT: ${GRPC_PORT}
      DATABASE_DSN: ${DATABASE_DSN}
      TOKEN_TTL: ${TOKEN_TTL}
      CONFIG_PATH: "/app/authService/config/config.yaml"
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
    volumes:
      - ./authService/config:/app/config
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    command: [ "./auth-service", "--config", "/app/authService/config/config.yaml" ]



  notification-service:
    build:
      context: .
      dockerfile: ./notificationService/Dockerfile
    ports:
      - "50052:50052"
      - "8081:8081"
    depends_on:
      - kafka
    command: [ "./notification-service", "--config", "/app/notificationService/config/config.yaml" ]
volumes:
  db_data:
  redis_data:
