syntax = "proto3";

package progressbar;

option go_package = "leadIt.progressbar.v1;progressbarv1";

import "google/api/annotations.proto";

service ProgressBar {
  rpc CreateProgressBar(CreateProgressBarRequest) returns (CreateProgressBarResponse) {
    option(google.api.http) = {
      post: "/v1/progress-bars"
      body: "*"
    };
  }

  rpc GetManyProgressBars(GetManyProgressBarsRequest) returns (GetManyProgressBarsResponse) {
    option(google.api.http) = {
      get: "/v1/projects/{project_id}/progress-bars"
    };
  }

  rpc DeleteProgressBar(DeleteProgressBarRequest) returns (DeleteProgressBarResponse) {
    option(google.api.http) = {
      delete: "/v1/progress-bars/{id}"
    };
  }
}

message ProgressBarType {
  int64 id = 1;
  string name = 2;
  int64 project_id = 3;
}

message CreateProgressBarRequest {
  string name = 1;
  int64 project_id = 2;
}

message CreateProgressBarResponse {
  int64 id = 1;
}

message GetManyProgressBarsRequest {
  int64 project_id = 1;
}

message GetManyProgressBarsResponse {
  repeated ProgressBarType progress_bar_list = 1;
}

message DeleteProgressBarRequest {
  int64 id = 1;
}

message DeleteProgressBarResponse {
  int64 id = 1;
}
