syntax = 'proto3';

package organization;

option go_package = "leadIt.organization.v1;organizationv1";
import "google/api/annotations.proto";


service Organization {
  rpc CreateOrganization (CreateOrganizationRequest) returns (CreateOrganizationResponse) {
    option(google.api.http) = {
      post: "/v1/organizations"
      body: "*"
    };
  }

  rpc GetOrganization(GetOrganizationRequest) returns (GetOrganizationResponse) {
    option (google.api.http) = {
      get: "/v1/organizations/{id}"
    };
  }

  rpc GetOrganizations(GetOrganizationsRequest) returns (GetOrganizationsResponse) {
    option(google.api.http) = {
      get: "/v1/users/{organizer_id}/organizations"
    };
  }

  rpc UpdateOrganization(UpdateOrganizationRequest) returns (UpdateOrganizationResponse) {
    option(google.api.http) = {
      patch: "/v1/organizations/{id}"
      body: "*"
    };
  }

  rpc DeleteOrganization(DeleteOrganizationRequest) returns (DeleteOrganizationResponse) {
    option(google.api.http) = {
      delete: "/v1/organizations/{id}"
    };
  }
}
message OrganizationType {
  int64 id = 1;
  string name = 2;
  int64 organizer_id = 3;
  string description = 4;
  string image = 5;
}

message CreateOrganizationRequest {
  string name = 1;
  string description = 2;
  string image = 3;
}

message CreateOrganizationResponse {
  int64 id = 1;
}

message GetOrganizationRequest {
  int64 id = 1;
}

message GetOrganizationResponse {
  OrganizationType organization = 1;
}

message GetOrganizationsRequest {
  int64 organizer_id = 1;
}

message GetOrganizationsResponse {
  repeated OrganizationType organizations = 1;
}

message UpdateOrganizationRequest {
  int64 id = 1;
  string name = 2;
  string description = 4;
  string image = 5;
}

message UpdateOrganizationResponse {
  OrganizationType organization = 1;
}

message DeleteOrganizationRequest {
  int64 id = 1;
}

message DeleteOrganizationResponse {
  int64 id = 1;
}