syntax = "proto3";

package employee;

option go_package = 'leadIt.employee.v1;employeev1';
import "google/api/annotations.proto";

service Employee {
  rpc CreateEmployee (CreateEmployeeRequest) returns (CreateEmployeeResponse) {
    option(google.api.http) = {
      post: "/v1/employees"
      body: "*"
    };
  }

  rpc GetEmployee(GetEmployeeRequest) returns (GetEmployeeResponse) {
    option(google.api.http) = {
      get: "/v1/employees/{id}"
    };
  }

  rpc GetEmployees(GetEmployeesRequest) returns (GetEmployeesResponse) {
    option(google.api.http) = {
      get: "/v1/organizations/{organization_id}/employees"
    };
  }

  rpc UpdateEmployeeRole(UpdateEmployeeRoleRequest) returns (UpdateEmployeeRoleResponse) {
    option(google.api.http) = {
      patch: "/v1/employees/{id}/role/{role_id}"
      body: "*"
    };
  }

  rpc DeleteEmployee(DeleteEmployeeRequest) returns (DeleteEmployeeResponse) {
    option(google.api.http) = {
      delete: "/v1/employees/{id}"
    };
  }

  rpc InviteEmployee(InviteEmployeeRequest) returns (InviteEmployeeResponse) {
    option(google.api.http) = {
      post: "/v1/employees/invite"
      body: "*"
    };
  }
}
message EmployeeType {
  int64 id = 1;
  int64 user_id = 2;
  int64 organization_id = 3;
}

message CreateEmployeeRequest {
  int64 user_id = 2;
  int64 organization_id = 3;
}

message CreateEmployeeResponse {
  int64 id = 1;
}

message GetEmployeeRequest {
  int64 id = 1;
}

message GetEmployeeResponse {
  EmployeeType employee = 1;
}

message GetEmployeesRequest {
  int64 organization_id = 1;
}

message GetEmployeesResponse {
  repeated EmployeeType employees = 1;
}

message UpdateEmployeeRoleRequest {
  int64 id = 1;
  int64 role_id = 2;
}

message UpdateEmployeeRoleResponse {
  int64 id = 1;
}

message DeleteEmployeeRequest {
  int64 id = 1;
}

message DeleteEmployeeResponse {
  int64 id = 1;
}

message InviteEmployeeRequest {
  int64 user_id = 1;
}

message InviteEmployeeResponse {
  bool success = 1;
}