syntax = "proto3";

package role;

option go_package = "leadIt.role.v1;rolev1";

import "google/api/annotations.proto";

service Role {
  rpc CreateRole(CreateRoleRequest) returns (CreateRoleResponse) {
    option(google.api.http) = {
      post: "/v1/roles"
      body: "*"
    };
  }

  rpc GetRole(GetRoleRequest) returns (GetRoleResponse) {
    option(google.api.http) = {
      get: "/v1/roles/{id}"
    };
  }

  rpc GetRoles(GetRolesRequest) returns (GetRolesResponse) {
    option(google.api.http) = {
      get: "/v1/organizations/{organization_id}/roles"
    };
  }

  rpc UpdateRole(UpdateRoleRequest) returns (UpdateRoleResponse) {
    option(google.api.http) = {
      patch: "/v1/roles/{id}"
      body: "*"
    };
  }

  rpc DeleteRole(DeleteRoleRequest) returns (DeleteRoleResponse) {
    option(google.api.http) = {
      delete: "/v1/roles/{id}"
    };
  }
}

message RoleType {
  int64 id = 1;
  string name = 2;
  int64 organization_id = 3;
  repeated string permissions = 4;
  int64 parent_role_id = 5;
}

message CreateRoleRequest {
  string name = 1;
  int64 organization_id = 2;
  repeated string permissions = 3;
  int64 parent_role_id = 4;
}

message CreateRoleResponse {
  int64 id = 1;
}

message GetRoleRequest {
  int64 id = 1;
}

message GetRoleResponse {
  RoleType role = 1;
}

message GetRolesRequest {
  int64 organization_id = 1;
}

message GetRolesResponse {
  repeated RoleType roles = 1;
}

message UpdateRoleRequest {
  int64 id = 1;
  string name = 2;
  repeated string permissions = 4;
  int64 parent_role_id = 5;
}

message UpdateRoleResponse {
  RoleType role = 1;
}

message DeleteRoleRequest {
  int64 id = 1;
}

message DeleteRoleResponse {
  int64 id = 1;
}
