env: "local"
storage_path: "./storage/agile.db"
storage_connection_string: "postgres://postgres:postgres@agiledb:5432/taskdb?sslmode=disable"
redis_connection_string: "redis://redis:6379"
token_secret: "super_secret_token"
grpc:
  port: 57448
  timeout: 10h