env: "local"
storage_path: "./storage/auth.db"
storage_connection_string: "postgres://postgres:postgres@localhost:5433/authdb?sslmode=disable"
token_ttl: 1h
refresh_token_ttl: 168h
grpc:
  port: 57442
  timout: 10h
