syntax = 'proto3';

package project;

option go_package = "leadIt.project.v1;projectv1";
import 'google/api/annotations.proto';

service Project {
  rpc CreateProject (CreateProjectRequest) returns (CreateProjectResponse) {
    option(google.api.http) = {
      post: "/v1/projects"
      body: "*"
    };
  }

  rpc GetProject(GetProjectRequest) returns (GetProjectResponse) {
    option(google.api.http) = {
      get: "/v1/projects/{id}"
    };
  }

  rpc GetProjects(GetProjectsRequest) returns (GetProjectsResponse) {
    option(google.api.http) = {
      get: "/v1/organizations/{organization_id}/projects"
    };
  }

  rpc UpdateProject(UpdateProjectRequest) returns (UpdateProjectResponse) {
    option(google.api.http) = {
      patch: "/v1/projects/{id}"
      body: "*"
    };
  }

  rpc DeleteProject(DeleteProjectRequest) returns (DeleteProjectResponse) {
    option(google.api.http) = {
      delete: "/v1/projects/{id}"
    };
  }
}

message ProjectType {
  int64 id = 1;
  string name = 2;
  string description = 3;
  int64 organization_id = 4;
  string image = 5;
}

message CreateProjectRequest {
  string name = 1;
  string description = 2;
  int64 organization_id = 3;
  string image = 4;
}

message CreateProjectResponse {
  int64 id = 1;
}

message GetProjectRequest {
  int64 id = 1;
}

message GetProjectResponse {
  ProjectType project = 1;
}

message GetProjectsRequest {
  int64 organization_id = 1;
}

message GetProjectsResponse {
  repeated ProjectType projects = 1;
}

message UpdateProjectRequest {
  int64 id = 1;
  string name = 2;
  string description = 3;
  string image = 5;
}

message UpdateProjectResponse {
  ProjectType project = 1;
}

message DeleteProjectRequest {
  int64 id = 1;
}

message DeleteProjectResponse {
  int64 id = 1;
}

