services:
  authdb:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  auth-service:
    build: .
    restart: always
    depends_on:
      - authdb
    environment:
      ENV: ${ENV}
      GRPC_PORT: ${GRPC_PORT}
      DATABASE_DSN: ${DATABASE_DSN}
      TOKEN_TTL: ${TOKEN_TTL}
      CONFIG_PATH: "/app/backend/config/config.yaml"
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
    volumes:
      - ./backend/config:/app/config
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    command: [ "./auth-service" ]

volumes:
  db_data:
