version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5433"

  auth-service:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      ENV: ${ENV}
      GRPC_PORT: ${GRPC_PORT}
      DATABASE_DSN: ${DATABASE_DSN}
      TOKEN_TTL: ${TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - ./internal/migrations:/migrations
    command: ["./auth-service"]

volumes:
  db_data:
